@baseUrl = http://localhost:8080

### Health Check
GET {{baseUrl}}/health
Accept: application/json

### Create Application
# @name createApplication
POST {{baseUrl}}/api/v1/applications
Content-Type: application/json

{
  "name": "PayNova"
}

### Get Application by ID
@appId = {{createApplication.response.body.id}}
GET {{baseUrl}}/api/v1/applications/{{appId}}
Accept: application/json

### Verify API Key
@apiKey = {{createApplication.response.body.api_key}}
GET {{baseUrl}}/api/v1/auth/verify
Authorization: Bearer {{apiKey}}
Accept: application/json

### Create Endpoint
# @name createEndpoint
POST {{baseUrl}}/api/v1/endpoints
Authorization: Bearer {{apiKey}}
Content-Type: application/json

{
  "url": "https://api.zara.com/webhooks",
  "description": "Zara Fulfillment Webhook"
}

### List Endpoints
GET {{baseUrl}}/api/v1/endpoints
Authorization: Bearer {{apiKey}}
Accept: application/json

### Get Endpoint by ID
@endpointId = {{createEndpoint.response.body.id}}
GET {{baseUrl}}/api/v1/endpoints/{{endpointId}}
Authorization: Bearer {{apiKey}}
Accept: application/json

### Update Endpoint
PUT {{baseUrl}}/api/v1/endpoints/{{endpointId}}
Authorization: Bearer {{apiKey}}
Content-Type: application/json

{
  "description": "Zara Fulfillment (Paused)",
  "status": "inactive"
}

### Delete Endpoint
DELETE {{baseUrl}}/api/v1/endpoints/{{endpointId}}
Authorization: Bearer {{apiKey}}
